### ISSUE TITLE
AnimatedNavHost transitions can be easily broken.

### ISSUE THREAD

**Issue by michaldrabik** [olshevski/compose-navigation-reimagined#15]
Not sure if this qualifies as library bug but it's quite easy to break the whole navigation if there are transitions involved.

It can be easily noticed in your BottomNavigation Demo. Just start spamming between any of 2 screens and you end up with navigation unresponsive.

Could it be that any ongoing transitions are not being cancelled prior to navigation action?

**Comment by olshevski** [comment]
@michaldrabik Hi. This is an issue in the library. Thanks for reporting, I've fixed it. You can use the snapshot with the fix:

```
repositories {
    maven(url = "https://s01.oss.sonatype.org/content/repositories/snapshots/")
}
```

```
implementation("dev.olshevski.navigation:reimagined:1.3.2-20230223.191530-1")
```

The expected behaviour: every transition should be queued and played one-by-one sequentially, even when the queue gets long due to action spamming. Any previous transition is not cancelled as it may result in an unpleasing/glitchy visuals.

**Comment by michaldrabik** [comment]
Thank you for swift response. We will test it out.

We also noticed similar behaviour with Modal navigation. When we open and close the sheet rapidly (by tapping background which triggers dismiss callback) it's also possible that the sheet will stay visible and navController no longer reacts.

Perhaps this is related and could be double checked as well?

**Comment by olshevski** [comment]
@michaldrabik I cannot reproduce it for BottomSheetNavHost in the version 1.3.1. I'm opening and closing the bottom sheet in the demo app as fast as I can, but it doesn't break. Maybe there are other precondition needed for reproducing it.

Can you please check if the fix resolves the issue with bottom sheets on your side? It seems to me that that it may have been caused by the same bug.

**Comment by michaldrabik** [comment]
Yeah, unfortunately it can't be reproduced in the demo sample. The snapshot version does not seem to fix the issue for us too.  Unfortunately I can't post code samples or even video due to policies.

But the bottom navigation issue originally reported is fixed although It feels kind of weird that after quickly switching between 2 destinations you need to wait until scheduled transitions will finish : )

**Comment by olshevski** [comment]
@michaldrabik 

>Yeah, unfortunately it can't be reproduced in the demo sample. The snapshot version does not seem to fix the issue for us too. Unfortunately I can't post code samples or even video due to policies.

Can you maybe make a simple app showing this issue which I can use to reproduce it?

**Comment by michaldrabik** [comment]
@olshevski Please see attached clip (cut out some non-crucial portion):

https://user-images.githubusercontent.com/11537045/221478576-01525aa4-fa7d-4ebd-9144-1bc95cbcb764.mov

3 first slowly clicks open and dismiss modal just fine but 4th all I need to do is click background to dismiss while modal is still coming up and I end up with it visible and navigation now broken.

**Comment by olshevski** [comment]
@michaldrabik Can you please also tell what version of Compose are you using in the app? BOM or versions of each used artifact will do.

**Comment by michaldrabik** [comment]
@olshevski 

        compose_version = "1.4.0-beta01"
        compose_compiler_version = "1.4.2"
        material_version = "1.8.0" (com.google.android.material:material)

**Comment by olshevski** [comment]
@michaldrabik Nope, still cannot reproduce it. I've played around with different sheet sizes, layouts, times between clicks (even automated it a bit). Tested on different compose versions.

It must be something else that might cause this issue, not sure what it could be. Is there any chance that you can show how BottomSheetNavHost is set up in your code (just the barebones, without any sensitive information)? Maybe it is some parameters that affect the behaviour, or the parent composable.

**Comment by michaldrabik** [comment]
@olshevski Basically it's like MainActivity with setContent :

```kotlin
        setContent {
// ...
                        MainNavEntryPoint()
                        ModalNavEntryPoint()
        }
```

where 

```kotlin
    @Composable
    @OptIn(ExperimentalAnimationApi::class)
    private fun MainNavEntryPoint() {
        val navController = rememberNavController<NavDestination>(MainDestination.Main)

        NavBackHandler(navController)

        AnimatedNavHost(
            controller = navController,
            transitionSpec = { action, _, _ ->
                navEnterTransition(action) with navExitTransition(action)
            }
        ) {
            if (it is MainDestination.Main) {
                MainScreen(screenProviders = screenProviders)
            } else {
                screenProviders.ScreenContent(destination = it)
            }
        }
    }
```

```kotlin
    @Composable
    @OptIn(ExperimentalMaterialApi::class)
    private fun ModalNavEntryPoint() {
        val navController = rememberNavController<NavDestination>(emptyList())

        BottomSheetNavHost(
            controller = navController,
            scrimColor = Color.Black.copy(alpha = 0.60f),
            sheetBackgroundColor = SomeTheme.colors.primaryBackgroundColor,
            sheetShape = RoundedCornerShape(topStart = 10.dp, topEnd = 10.dp),
            sheetPropertiesSpec = {
                BottomSheetProperties(
                    isSkipHalfExpanded = true
                )
            },
            onDismissRequest = { navController.pop() }
        ) {
            screenProviders.ScreenContent(destination = it)
        }
    }
```

**Comment by michaldrabik** [comment]
@olshevski Actually, yes. The issue seems to be non-existent in that snapshot 🥇

**Comment by olshevski** [comment]
@michaldrabik Great!

I've also worked on a new alternative queueing strategy that may be more suitable for some cases (as for BottomNavigation). There is another new snapshot (another day another snapshot heh):

```
implementation("dev.olshevski.navigation:reimagined:1.4.0-20230302.163310-2")
```

This snapshot adds a new parameter to AnimatedNavHost. You can specify `transitionQueueing = NavTransitionQueueing.Conflate` and it will skip as many pending transitions as possible. This way there wouldn't be this ridiculous queue of animations if a user spams buttons.

You may check it out as well if you want.

**Comment by michaldrabik** [comment]
@olshevski Thanks, do you expect a non-snapshot release anytime soon?

**Comment by michaldrabik** [comment]
@olshevski Got it. Thanks. 

We're very happy with migrating from Voyager to Reimagined anyway as it appears to have none of lifecycle problems Voyager has (and still not fixed - seems abandoned), so great job anyway. Kind of hesitant with using snapshots in our releases so will just wait until proper one. Kind regards.

**Comment by olshevski** [comment]
@michaldrabik Sorry for the long wait. I've finally release a new version today. It includes all the discussed fixes.

Please note that there is a breaking change in BottomSheetNavHost - couldn't come up with a reasonable backward-compatibility for it: you need to specify a Surface inside BottomSheetNavHost manually now, like this:

```kotlin
BottomSheetNavHost(
    controller = sheetController,
    onDismissRequest = { sheetController.pop() }
) { destination ->
    Surface(
        elevation = ModalBottomSheetDefaults.Elevation
    ) {
        when (destination) {
            /* ... */
        }
    }
}
```

There is also no need for specifying`transitionQueueing = NavTransitionQueueing.Conflate` for AnimatedNavHost (as in the bottom navigation case). I decided that there is no need to have the transition queueing by default. But it may be enabled if anyone needs it.

**Comment by michaldrabik** [comment]
Graet. Thanks for all your work.
